from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class ScopeCase:
    cid: str
    desc: str
    set_url: str
    header: str
    request_url: Optional[str]
    expect_accept: bool
    expect_code: str
    expect_sent: Optional[bool]


CASES = [
    ScopeCase("SC-01", "主机精确匹配（host-only 默认）",
              "https://example.com/", "sid=1; Path=/",
              "https://example.com/", True, "OK", True),
    ScopeCase("SC-02", "host-only Cookie 不下发到子域",
              "https://example.com/", "sid=1; Path=/",
              "https://sub.example.com/", True, "OK", False),
    ScopeCase("SC-03", "Domain 属性覆盖子域",
              "https://example.com/", "sid=1; Domain=example.com; Path=/",
              "https://sub.example.com/", True, "OK", True),
    ScopeCase("SC-04", "子域设置父域（合法上溯）",
              "https://sub.example.com/", "sid=1; Domain=example.com; Path=/",
              "https://example.com/", True, "OK", True),
    ScopeCase("SC-05", "父域设置子域（越权下钻）",
              "https://example.com/", "sid=1; Domain=sub.example.com",
              None, False, "INVALID_DOMAIN", None),
    ScopeCase("SC-06", "前缀相似但不同域 notexample.com",
              "https://example.com/", "sid=1; Domain=example.com; Path=/",
              "https://notexample.com/", True, "OK", False),
    ScopeCase("SC-07", "连字符相似域 evil-example.com",
              "https://example.com/", "sid=1; Domain=example.com; Path=/",
              "https://evil-example.com/", True, "OK", False),
    ScopeCase("SC-08", "Domain 是主机后缀但无点边界 ample.com",
              "https://example.com/", "sid=1; Domain=ample.com",
              None, False, "INVALID_DOMAIN", None),
    ScopeCase("SC-09", "域名大小写不敏感",
              "https://WWW.EXAMPLE.COM/", "sid=1; Domain=EXAMPLE.com; Path=/",
              "https://example.com/", True, "OK", True),
    ScopeCase("SC-10", "Domain 前导点被剥离",
              "https://example.com/", "sid=1; Domain=.example.com; Path=/",
              "https://sub.example.com/", True, "OK", True),
    ScopeCase("SC-11", "公共后缀 com 拒绝",
              "https://example.com/", "sid=1; Domain=com",
              None, False, "PUBLIC_SUFFIX", None),
    ScopeCase("SC-12", "公共后缀 co.uk 拒绝",
              "https://shop.example.co.uk/", "sid=1; Domain=co.uk",
              None, False, "PUBLIC_SUFFIX", None),
    ScopeCase("SC-13", "公共后缀之下的可注册域正常",
              "https://shop.example.co.uk/", "sid=1; Domain=example.co.uk; Path=/",
              "https://www.example.co.uk/", True, "OK", True),
    ScopeCase("SC-14", "IPv4 字面量精确匹配",
              "http://127.0.0.1/", "sid=1; Path=/",
              "http://127.0.0.1/", True, "OK", True),
    ScopeCase("SC-15", "IPv4 字面量不做后缀匹配",
              "http://127.0.0.1/", "sid=1; Domain=127.0.0.1; Path=/",
              "http://127.0.0.2/", True, "OK", False),
    ScopeCase("SC-16", "IPv4 Domain 属性与主机相等可接受",
              "http://127.0.0.1/", "sid=1; Domain=127.0.0.1; Path=/",
              "http://127.0.0.1/", True, "OK", True),
    ScopeCase("SC-17", "IPv4 Domain 属性后缀欺骗 0.0.1",
              "http://127.0.0.1/", "sid=1; Domain=0.0.1",
              None, False, "IP_LITERAL_MISMATCH", None),
    ScopeCase("SC-18", "端口不参与作用域隔离",
              "http://example.com:8080/", "sid=1; Path=/",
              "http://example.com:9090/", True, "OK", True),
    ScopeCase("SC-19", "路径前缀陷阱 /foo 不匹配 /foobar",
              "https://example.com/foo", "sid=1; Path=/foo",
              "https://example.com/foobar", True, "OK", False),
    ScopeCase("SC-20", "路径前缀合法下延 /foo/bar",
              "https://example.com/foo", "sid=1; Path=/foo",
              "https://example.com/foo/bar", True, "OK", True),
    ScopeCase("SC-21", "路径精确匹配 /foo",
              "https://example.com/foo", "sid=1; Path=/foo",
              "https://example.com/foo", True, "OK", True),
    ScopeCase("SC-22", "Path=/foo/ 不匹配 /foo",
              "https://example.com/foo/", "sid=1; Path=/foo/",
              "https://example.com/foo", True, "OK", False),
    ScopeCase("SC-23", "默认路径推导 /account/login -> /account",
              "https://example.com/account/login", "sid=1",
              "https://example.com/account/settings", True, "OK", True),
    ScopeCase("SC-24", "默认路径边界 /account 不匹配 /accountant",
              "https://example.com/account/login", "sid=1",
              "https://example.com/accountant", True, "OK", False),
    ScopeCase("SC-25", "单段 URI 默认路径为 /",
              "https://example.com/login", "sid=1",
              "https://example.com/anything", True, "OK", True),
    ScopeCase("SC-26", "IPv6 字面量精确匹配（端口忽略）",
              "http://[::1]:8080/", "sid=1; Path=/",
              "http://[::1]:9090/", True, "OK", True),
    ScopeCase("SC-27", "公共后缀即主机本身时按 host-only 接受",
              "https://appspot.com/", "sid=1; Domain=appspot.com; Path=/",
              "https://appspot.com/", True, "OK", True),
    ScopeCase("SC-28", "公共后缀子域试图设置父后缀 appspot.com",
              "https://myapp.appspot.com/", "sid=1; Domain=appspot.com",
              None, False, "PUBLIC_SUFFIX", None),
    ScopeCase("SC-29", "空 Domain 属性按缺省 host-only 处理",
              "https://example.com/", "sid=1; Domain=; Path=/",
              "https://sub.example.com/", True, "OK", False),
    ScopeCase("SC-30", "主机尾点规范化 example.com. == example.com",
              "https://example.com./", "sid=1; Path=/",
              "https://example.com/", True, "OK", True),
]
